repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-added-large-files
        args:
          - "--maxkb=2048"
          - "--enforce-all"
      - id: check-case-conflict
      - id: check-json
        exclude: 'tsconfig.*\.json$'
      - id: check-yaml
        args:
          - "--unsafe"
        exclude: pnpm-lock.yaml
      - id: detect-aws-credentials
        args:
          - "--allow-missing-credentials"
      - id: detect-private-key
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [-c=./.config/.yamllint.yaml]
        exclude: 'pnpm-lock\.yaml|^\.github/'

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".config/.secrets.baseline"]
        exclude: .config/.secrets.baseline

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: node_modules/.bin/prettier --write --ignore-unknown
        language: system
        files: \.(ts|js|json|yaml|yml|md)$
        exclude: pnpm-lock.yaml

      - id: typecheck
        name: typecheck
        entry: pnpm run typecheck
        language: system
        types: [ts]
        pass_filenames: false
